# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20180917_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Priority',
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={},
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='category',
            new_name='priority',
        ),
    ]
